### ISSUE TITLE
fatal error after latest update

### ISSUE THREAD

**Issue by townkat** [MOROway/moroway-app-oc#3]
hi,
i just discovered this game yesterday, and wanted to play it again today, but decided to update it first as i was hoping for the panning (and controls/touch) to be improved
now, i get fatal error (red/black screen) after latest update, 
i have galaxy s5 (klte) with latest lineage os 18.1 (android 11), i installed the game from f-droid
thank you

**Comment by jonathanherrmannengel** [comment]
Yes, thank you.

I messed up F-Droid build instructions for v7.2.4. Hopefully https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9931 will fix build process with new version 7.2.5. Panning improvements are scheduled for v7.3.0 which will be released as soon as build process is fixed.

Am 16. Oktober 2021 10:32:11 UTC schrieb townkat ***@***.***>:

**Comment by townkat** [comment]
no problem, 
just wanted to make sure the problem gets noticed
i will look forward to play it again then,

thank you alot for your contribution 👍

**Comment by jonathanherrmannengel** [comment]
thanks again, fixed version is live
